version: '3.8'

services:
  fastapi:
    build:
      context: ./app
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
